### ISSUE TITLE
Broken Link on Spash Page

### ISSUE THREAD

**Issue by DeannaCaracciolo** [orcoastalmgmt/habitatscreeningtool#7]
Currently linked to - https://www.oregon.gov/LCD/OCMP/Pages/Federal_Consistency_Home.aspx
Should be linked to - https://www.oregon.gov/LCD/OCMP/Pages/Federal-Consistency.aspx

**Comment by tchaddad** [comment]
Hi Deanna, I've just fixed this bug - please test on your end to confirm if it's working for you, and then you can come back here and close this issue!

**Comment by DeannaCaracciolo** [comment]
Wow!  You’re so quick!  Thanks Tanya – it worked for me!
